[package]
name = "box-it"
authors = ["Craig Ponton <craig.ponton@bdatad.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "3.3.3"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
